steps:
  - id: "Executar os testes"
    name: "gcr.io/cloud-builders/go:alpine"
    args: ["test", "./..."]

  - id: "Build da aplicação"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/desafio_go_ci:latest"]

images:
  - "gcr.io/$PROJECT_ID/desafio_go_ci:latest"
